'use client';
import * as React from 'react';
import Link from 'next/link';
import { CheckCircle2, Star } from 'lucide-react';

export default function FeedbackPage(){
  const [doctors,setDoctors]=React.useState<any[]>([]); const [doctorId,setDoctorId]=React.useState(''); const [rating,setRating]=React.useState(5); const [comment,setComment]=React.useState(''); const [message,setMessage]=React.useState('');
  React.useEffect(()=>{fetch('/api/catalog').then(r=>r.json()).then(data=>{setDoctors(data.doctors||[]);setDoctorId(data.doctors?.[0]?.id||'');});},[]);
  const submit=async()=>{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({doctorId,rating,comment})});const data=await response.json();setMessage(response.ok?'Cảm ơn bạn. Đánh giá đã được ghi nhận.':data.detail);if(response.ok)setComment('');};
  return <div className="clinic-page"><section className="mx-auto max-w-3xl rounded-[28px] border border-[#d8e4df] bg-white p-9 shadow-[0_18px_55px_rgba(27,78,69,.08)]"><span className="clinic-kicker">Phản hồi người bệnh</span><h1 className="mt-3 text-4xl">Đánh giá trải nghiệm thăm khám</h1><p className="mt-3 text-sm leading-6 text-[#60736f]">Ý kiến được tổng hợp theo bác sĩ và chuyên khoa để phòng khám cải thiện chất lượng phục vụ.</p><div className="mt-8 space-y-5"><label className="block text-xs font-bold text-[#526a65]">Bác sĩ<select value={doctorId} onChange={e=>setDoctorId(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-[#c7ded7] bg-white px-4 text-sm">{doctors.map(d=><option key={d.id} value={d.id}>{d.specialtyName} · {d.name}</option>)}</select></label><div><span className="text-xs font-bold text-[#526a65]">Mức độ hài lòng</span><div className="mt-2 flex gap-2">{[1,2,3,4,5].map(score=><button key={score} onClick={()=>setRating(score)} aria-label={`${score} sao`} className={`grid h-11 w-11 place-items-center rounded-xl border ${score<=rating?'border-[#e1ad28] bg-[#fff3c9] text-[#bf7c00]':'border-[#d8e4df] text-[#9baaa6]'}`}><Star className="h-5 w-5" fill={score<=rating?'currentColor':'none'}/></button>)}</div></div><label className="block text-xs font-bold text-[#526a65]">Nhận xét<textarea rows={5} value={comment} onChange={e=>setComment(e.target.value)} className="mt-2 w-full rounded-xl border border-[#c7ded7] p-4 text-sm" placeholder="Điều gì phòng khám đã làm tốt hoặc cần cải thiện?"/></label><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-bold text-[#087f73]">{message&&<CheckCircle2 className="h-4 w-4"/>}{message}</span><button onClick={submit} className="rounded-xl bg-[#087f73] px-6 py-3 text-sm font-bold text-white">Gửi đánh giá</button></div><p className="text-xs text-[#60736f]">Bạn chưa đăng nhập? <Link href="/dang-nhap?returnUrl=/danh-gia" className="font-bold text-[#075f59]">Đăng nhập tại đây</Link>.</p></div></section></div>;
}
