'use client';
import { ArrowUpRight, CalendarDays, Package, Wrench } from 'lucide-react';
import { displayDate, STATUS_LABELS, vietnamDate } from '@/lib/admin-labels';
export type Operations={today:string;daily:Array<{status:string;count:number}>;totals:Array<{status:string;count:number}>;trend:Array<{date:string;count:number}>;upcoming:Array<{id:string;patient_name:string;appointment_time:string;status:string;specialty_name:string}>;lowStock:Array<{id:string;name:string;current_quantity:number;minimum_quantity:number;unit:string;expiry_date:string|null}>;maintenance:Array<{id:string;asset_name:string;next_maintenance_date:string;status:string}>;chat:Array<{id:string;patient_name:string;doctor_name:string;status:string;channel_type:string;message_count:number;last_message_at:number;created_at:number}>};
export function AdminOverview({data,navigate,reports=false}:{data:Operations;navigate:(key:string)=>void;reports?:boolean}) {
  const stats=reports?data.totals:data.daily;
  const count=(status:string)=>stats.find(s=>s.status===status)?.count||0;
  const days=Array.from({length:7},(_,i)=>{const date=vietnamDate(new Date(Date.now()-(6-i)*86400000));return {date,count:data.trend.find(d=>d.date===date)?.count||0};});
  const max=Math.max(1,...days.map(d=>d.count));
  return <div className="admin-overview">
    <div className="admin-stat-grid">{[['Lịch hẹn'+(reports?' toàn kỳ':' hôm nay'),stats.reduce((sum,s)=>sum+s.count,0)],['Chờ xác nhận',count('pending')],['Đang chờ khám',count('checked_in')],['Đã hoàn thành',count('completed')]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{reports?'Tất cả lịch hẹn đã ghi nhận':displayDate(data.today)}</small></div>)}</div>
    <div className="admin-overview-grid"><section className="admin-panel"><header><div><span className="admin-eyebrow">Hoạt động tiếp nhận</span><h3>Lịch hẹn trong 7 ngày</h3></div><span className="admin-badge">{days.reduce((sum,d)=>sum+d.count,0)} lịch hẹn</span></header><div className="admin-chart" role="img" aria-label={days.map(d=>`${displayDate(d.date)}: ${d.count} lịch hẹn`).join('; ')}>{days.map(d=><div key={d.date}><strong>{d.count}</strong><div><i style={{height:`${Math.max(2,d.count/max*100)}%`}}/></div><small>{displayDate(d.date).slice(0,5)}</small></div>)}</div><p className="admin-muted">Tính theo ngày khám, bao gồm lịch đã hủy. Không phải số lượt khám hoàn thành.</p></section>
    <section className="admin-panel"><header><div><span className="admin-eyebrow">Ưu tiên xử lý</span><h3>Cần chú ý hôm nay</h3></div></header><button className="admin-task" onClick={()=>navigate('appointments')}><CalendarDays/><span><strong>{count('pending')} lịch chờ xác nhận</strong><small>Mở danh sách để tiếp nhận người bệnh</small></span><ArrowUpRight size={17}/></button><button className="admin-task" onClick={()=>navigate('inventory')}><Package/><span><strong>Thuốc & vật tư</strong><small>{data.lowStock.length?`${data.lowStock.length} cảnh báo đang hiển thị`:'Chưa có cảnh báo tồn hoặc hạn dùng'}</small></span><ArrowUpRight size={17}/></button><button className="admin-task" onClick={()=>navigate('maintenance')}><Wrench/><span><strong>Thiết bị & bảo trì</strong><small>{data.maintenance.length?`${data.maintenance.length} thiết bị cần theo dõi`:'Chưa có lịch bảo trì cần xử lý'}</small></span><ArrowUpRight size={17}/></button></section></div>
    <section className="admin-panel"><header><div><span className="admin-eyebrow">Tiếp nhận hôm nay</span><h3>Lịch hẹn chưa kết thúc</h3></div><button className="admin-button" onClick={()=>navigate('appointments')}>Xem tất cả <ArrowUpRight size={15}/></button></header>{data.upcoming.length?<div className="admin-table-scroll"><table><thead><tr><th>Giờ khám</th><th>Người bệnh</th><th>Chuyên khoa</th><th>Trạng thái</th></tr></thead><tbody>{data.upcoming.map(a=><tr key={a.id}><td><strong>{a.appointment_time}</strong></td><td>{a.patient_name}</td><td>{a.specialty_name}</td><td><span className="admin-badge">{STATUS_LABELS[a.status]||a.status}</span></td></tr>)}</tbody></table></div>:<div className="admin-empty">Chưa có lịch hẹn đang chờ trong hôm nay.</div>}</section>
    {(data.lowStock.length>0||data.maintenance.length>0)&&<div className="admin-overview-grid"><section className="admin-panel"><h3>Chi tiết cảnh báo kho</h3>{data.lowStock.map(item=><div className="admin-alert-row" key={item.id}><strong>{item.name}</strong><span>{item.current_quantity} {item.unit} · Mức tối thiểu {item.minimum_quantity}</span>{item.expiry_date&&item.expiry_date<=data.today&&<span className="admin-badge danger">Hạn dùng {displayDate(item.expiry_date)}</span>}</div>)}</section><section className="admin-panel"><h3>Theo dõi bảo trì</h3>{data.maintenance.map(item=><div className="admin-alert-row" key={item.id}><strong>{item.asset_name}</strong><span>{displayDate(item.next_maintenance_date)} · {STATUS_LABELS[item.status]||item.status}</span></div>)}</section></div>}
  </div>;
}
